AllCops:
  TargetRubyVersion: 3.4.4

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  Exclude:
    - "lib/tenji/converter.rb"

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
