AllCops:
  TargetRubyVersion: 3.1

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  Exclude:
    - "lib/tenji/converter.rb"

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - spec/**/*
  ExcludedMethods:
    - convert_to_tenji

Metrics/AbcSize:
  ExcludedMethods:
    - convert_to_tenji
    - braille_mirror

Metrics/CyclomaticComplexity:
  ExcludedMethods:
    - convert_to_tenji
    - braille_mirror

Metrics/PerceivedComplexity:
  ExcludedMethods:
    - convert_to_tenji

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
